
name: Build Project

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - My-portfile   # Change this if your branch name differs (case-sensitive)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js with caching for Yarn
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      # 3. Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 4. Build the project
      - name: Build project
        run: yarn build
